### ISSUE TITLE
Tighten up configuration

### ISSUE THREAD

**Issue by adamwight** [CoderKungfu/php-queue#42]
Interfaces\Config is unused.  Tests and demo applications should be locally configured with a single file config.yaml.example, rather than in code.

I don't know what the config data should look like.  It would be nice to include backend dependency injection, as well as defaults for each backend, but this seems like an overly complicated configuration file, it would look something like:
```
stomp:
    uri: tcp://host.localhost.net:61613
    read_timeout: 10

queues:
    test_stomp:
        backend: Stomp
```
